### ISSUE TITLE
pip and docs?

### ISSUE THREAD

**Issue by szabolcsdombi** [Queatz/glmpython#3]
Hello,

Is you module registered on [pypi](https://pypi.python.org/pypi)?
Do you have any documentation? [readthedocs.io](http://readthedocs.io/) or similar?

I am willing to add **glm** binding to some of the [ModernGL](https://github.com/cprogrammer1994/ModernGL) examples. It would be great if I could use this module.

_I can help with the pypi and docs part if you want._

**Comment by Queatz** [comment]
@cprogrammer1994 I haven't touched this for about 5 years.  Not sure how much has changed in GLM since then!  Don't currently have plans to write docs or release it (I've never released anything on pypi before).  If you want to give it a shot, by all means, go for it.

ModernGL looks cool btw! :)
